-- Shopping Tool Supabase schema
-- Run this in the Supabase SQL Editor for the project you create.

create table if not exists tracked_products (
  id bigint generated by default as identity primary key,
  url text not null unique,
  shop text not null,
  title text not null,
  image_type text not null default 'bag',
  image_label text not null default 'New',
  image_url text,
  current_price text not null default 'Waiting for scraper',
  previous_price text not null default 'None yet',
  currency text,
  tracked_size text not null default '',
  variant_specs text not null default '',
  size_label text not null default 'Unknown',
  stock_status text not null default 'Unknown',
  stock_scope text not null default 'general',
  latest_change text not null default '',
  badges_json jsonb not null default '[]'::jsonb,
  last_checked_at text not null default 'Not checked yet',
  last_scrape_source text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists product_snapshots (
  id bigint generated by default as identity primary key,
  product_id bigint not null references tracked_products(id) on delete cascade,
  price text,
  stock_status text,
  size_label text,
  title text,
  image_url text,
  raw_source text,
  stock_scope text not null default 'general',
  checked_at timestamptz not null default now()
);

create table if not exists product_events (
  id bigint generated by default as identity primary key,
  product_id bigint not null references tracked_products(id) on delete cascade,
  event_type text not null,
  message text not null,
  created_at timestamptz not null default now(),
  emailed_at timestamptz
);

create table if not exists app_settings (
  key text primary key,
  value text not null,
  updated_at timestamptz not null default now()
);

create index if not exists product_snapshots_product_id_checked_at_idx
  on product_snapshots (product_id, checked_at desc);

create index if not exists product_events_product_id_created_at_idx
  on product_events (product_id, created_at desc);

create or replace function set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists tracked_products_set_updated_at on tracked_products;

create trigger tracked_products_set_updated_at
before update on tracked_products
for each row
execute function set_updated_at();

-- Keep tables private by default. The app will access them from server-side
-- code using a Supabase service role key stored in environment variables.
alter table tracked_products enable row level security;
alter table product_snapshots enable row level security;
alter table product_events enable row level security;
alter table app_settings enable row level security;
